### ISSUE TITLE
error while running

### ISSUE THREAD

**Issue by chawdamrunal** [monnappa22/Limon#17]
Traceback (most recent call last):
  File "limon.py", line 27, in <module>
    from statan import *
  File "/home/mrunal/Limon/statan.py", line 27, in <module>
    import magic
ImportError: No module named magic

**Comment by urwithajit9** [comment]
Install python magic module.
$pip install python-magic
And if you have installed it and still showing it means there is an issue with the Python version or account type. Check Python2 vs Python3 . sudo vs other user.
