### ISSUE TITLE
AttributeError: 'module' object has no attribute 'open'

### ISSUE THREAD

**Issue by AndrewZheng-AI** [monnappa22/Limon#2]
hello
when i start to run, i get bellow errors
Traceback (most recent call last):
  File "limon.py", line 168, in <module>
    filetype = static.filetype()
  File "/root/Limon/statan.py", line 46, in filetype
    m = magic.open(magic.MAGIC_NONE)
AttributeError: 'module' object has no attribute 'open'

i think maybe magic doesn't has open method
so i test it
python
import magic
dir(magic)
get: 
['MAGIC_CHECK', 'MAGIC_COMPRESS', 'MAGIC_CONTINUE', 'MAGIC_DEBUG', 'MAGIC_DEVICES', 'MAGIC_ERROR', 'MAGIC_MIME', 'MAGIC_MIME_ENCODING', 'MAGIC_NONE', 'MAGIC_NO_CHECK_APPTYPE', 'MAGIC_NO_CHECK_ASCII', 'MAGIC_NO_CHECK_COMPRESS', 'MAGIC_NO_CHECK_ELF', 'MAGIC_NO_CHECK_FORTRAN', 'MAGIC_NO_CHECK_SOFT', 'MAGIC_NO_CHECK_TAR', 'MAGIC_NO_CHECK_TOKENS', 'MAGIC_NO_CHECK_TROFF', 'MAGIC_PRESERVE_ATIME', 'MAGIC_RAW', 'MAGIC_SYMLINK', 'Magic', 'MagicException', '**builtins**', '**doc**', '**file**', '**name**', '**package**', '_get_magic_type', '_instances', '_magic_buffer', '_magic_file', '_magic_load', 'c_char_p', 'c_int', 'c_size_t', 'c_void_p', 'coerce_filename', 'ctypes', 'dll', 'errorcheck_negative_one', 'errorcheck_null', 'from_buffer', 'from_file', 'glob', 'libmagic', 'magic_buffer', 'magic_check', 'magic_close', 'magic_compile', 'magic_errno', 'magic_error', 'magic_file', 'magic_load', 'magic_open', 'magic_setflags', 'magic_t', 'os', 'sys', 'threading']

not contatin open and load method

my env is:
Linux iZ230mc0fafZ 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Python 2.7.6
python-magic version: 0.4.10

**Comment by AndrewZheng-AI** [comment]
am i mistake somethings? or maybe the magic version

**Comment by monnappa22** [comment]
Hi,

Thanks for letting me know, I tested Limon on python 2.7.9 and you are using python 2.7.6 and it looks like python magic does not have open method in 2.7.6 but open method is present in 2.7.9 (which is weird). I have now fixed that issue to work for both versions and uploaded to Github. To solve that problem download the latest version and replace "statan.py" module with the new statan.py module. That should solve the problem. let me know if it solves the problem

Just for the information, below snippet shows the presence of open method is python 2.7.9

Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import magic
> > > dir(magic)
> > > ['APPLE', 'ARRAY', 'ArgumentError', 'Array', 'BigEndianStructure', 'CDLL', 'CFUNCTYPE', 'CHECK', 'COMPRESS', 'CONTINUE', 'DEBUG', 'DEFAULT_MODE', 'DEVICES', 'ERROR', 'LibraryLoader', 'LittleEndianStructure', 'MAGIC_APPLE', 'MAGIC_CHECK', 'MAGIC_COMPRESS', 'MAGIC_CONTINUE', 'MAGIC_DEBUG', 'MAGIC_DEVICES', 'MAGIC_ERROR', 'MAGIC_MIME', 'MAGIC_MIME_ENCODING', 'MAGIC_MIME_TYPE', 'MAGIC_NONE', 'MAGIC_NO_CHECK_APPTYPE', 'MAGIC_NO_CHECK_BUILTIN', 'MAGIC_NO_CHECK_CDF', 'MAGIC_NO_CHECK_COMPRESS', 'MAGIC_NO_CHECK_ELF', 'MAGIC_NO_CHECK_ENCODING', 'MAGIC_NO_CHECK_SOFT', 'MAGIC_NO_CHECK_TAR', 'MAGIC_NO_CHECK_TEXT', 'MAGIC_NO_CHECK_TOKENS', 'MAGIC_PRESERVE_ATIME', 'MAGIC_RAW', 'MAGIC_SYMLINK', 'MIME', 'MIME_ENCODING', 'MIME_TYPE', 'Magic', 'NONE', 'NO_CHECK_APPTYPE', 'NO_CHECK_BUILTIN', 'NO_CHECK_CDF', 'NO_CHECK_COMPRESS', 'NO_CHECK_ELF', 'NO_CHECK_ENCODING', 'NO_CHECK_SOFT', 'NO_CHECK_TAR', 'NO_CHECK_TEXT', 'NO_CHECK_TOKENS', 'POINTER', 'PRESERVE_ATIME', 'PYFUNCTYPE', 'PyDLL', 'RAW', 'RTLD_GLOBAL', 'RTLD_LOCAL', 'SYMLINK', 'SetPointerType', 'Structure', 'Union', '**builtins**', '**doc**', '**file**', '**name**', '**package**', '_buffer', '_check', '_close', '_compile', '_descriptor', '_errno', '_error', '_file', '_init', '_libraries', '_list', '_load', '_open', '_setflags', 'addressof', 'alignment', 'byref', 'c_bool', 'c_buffer', 'c_byte', 'c_char', 'c_char_p', 'c_double', 'c_float', 'c_int', 'c_int16', 'c_int32', 'c_int64', 'c_int8', 'c_long', 'c_longdouble', 'c_longlong', 'c_short', 'c_size_t', 'c_ssize_t', 'c_ubyte', 'c_uint', 'c_uint16', 'c_uint32', 'c_uint64', 'c_uint8', 'c_ulong', 'c_ulonglong', 'c_ushort', 'c_void_p', 'c_voidp', 'c_wchar', 'c_wchar_p', 'cast', 'cdll', 'create_string_buffer', 'create_unicode_buffer', 'ctypes', 'find_library', 'get_errno', 'magic_set', 'magic_t', 'memmove', 'memset', 'open', 'pointer', 'py_object', 'pydll', 'pythonapi', 'resize', 'set_conversion_mode', 'set_errno', 'sizeof', 'string_at', 'wstring_at']

**Comment by monnappa22** [comment]
Hi,

Thanks for letting me know, I had tested Limon on python 2.7.9 and you are
using python 2.7.6 and it looks like python magic does not have open method
in 2.7.6 but open method is present in 2.7.9 (which is weird). I have now
fixed that issue to work for both versions and uploaded to Github. To solve
that problem download the latest version and replace "statan.py" module
with the new statan.py module. That should solve the problem. let me know
if it solves the problem

Just for the information, below snippet shows the presence of open method
is python 2.7.9

Python 2.7.9 (default, Mar 1 2015, 12:57:24)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

import magic
dir(magic)
['APPLE', 'ARRAY', 'ArgumentError', 'Array', 'BigEndianStructure', 'CDLL',
'CFUNCTYPE', 'CHECK', 'COMPRESS', 'CONTINUE', 'DEBUG', 'DEFAULT_MODE',
'DEVICES', 'ERROR', 'LibraryLoader', 'LittleEndianStructure',
'MAGIC_APPLE', 'MAGIC_CHECK', 'MAGIC_COMPRESS', 'MAGIC_CONTINUE',
'MAGIC_DEBUG', 'MAGIC_DEVICES', 'MAGIC_ERROR', 'MAGIC_MIME',
'MAGIC_MIME_ENCODING', 'MAGIC_MIME_TYPE', 'MAGIC_NONE',
'MAGIC_NO_CHECK_APPTYPE', 'MAGIC_NO_CHECK_BUILTIN', 'MAGIC_NO_CHECK_CDF',
'MAGIC_NO_CHECK_COMPRESS', 'MAGIC_NO_CHECK_ELF', 'MAGIC_NO_CHECK_ENCODING',
'MAGIC_NO_CHECK_SOFT', 'MAGIC_NO_CHECK_TAR', 'MAGIC_NO_CHECK_TEXT',
'MAGIC_NO_CHECK_TOKENS', 'MAGIC_PRESERVE_ATIME', 'MAGIC_RAW',
'MAGIC_SYMLINK', 'MIME', 'MIME_ENCODING', 'MIME_TYPE', 'Magic', 'NONE',
'NO_CHECK_APPTYPE', 'NO_CHECK_BUILTIN', 'NO_CHECK_CDF',
'NO_CHECK_COMPRESS', 'NO_CHECK_ELF', 'NO_CHECK_ENCODING', 'NO_CHECK_SOFT',
'NO_CHECK_TAR', 'NO_CHECK_TEXT', 'NO_CHECK_TOKENS', 'POINTER',
'PRESERVE_ATIME', 'PYFUNCTYPE', 'PyDLL', 'RAW', 'RTLD_GLOBAL',
'RTLD_LOCAL', 'SYMLINK', 'SetPointerType', 'Structure', 'Union', '_builtins_',
'_doc_', '_file_', '_name_', '_package_', '_buffer', '_check', '_close',
'_compile', '_descriptor', '_errno', '_error', '_file', '_init',
'_libraries', '_list', '_load', '_open', '_setflags', 'addressof',
'alignment', 'byref', 'c_bool', 'c_buffer', 'c_byte', 'c_char', 'c_char_p',
'c_double', 'c_float', 'c_int', 'c_int16', 'c_int32', 'c_int64', 'c_int8',
'c_long', 'c_longdouble', 'c_longlong', 'c_short', 'c_size_t', 'c_ssize_t',
'c_ubyte', 'c_uint', 'c_uint16', 'c_uint32', 'c_uint64', 'c_uint8',
'c_ulong', 'c_ulonglong', 'c_ushort', 'c_void_p', 'c_voidp', 'c_wchar',
'c_wchar_p', 'cast', 'cdll', 'create_string_buffer',
'create_unicode_buffer', 'ctypes', 'find_library', 'get_errno',
'magic_set', 'magic_t', 'memmove', 'memset', 'open', 'pointer',
'py_object', 'pydll', 'pythonapi', 'resize', 'set_conversion_mode',
'set_errno', 'sizeof', 'string_at', 'wstring_at']

**Comment by AndrewZheng-AI** [comment]
thks for your work
before see that, i change the code 
vim statan.py
def filetype(self):
    if os.path.exists(self.file):
        #m = magic.open(magic.MAGIC_NONE)
        #m.load()
        ftype = magic.from_file(self.file, mime=True)
        return ftype
    else:
        print "No such file or directory:", self.file
        sys.exit()

it looks like works
but i will update your git update

**Comment by monnappa22** [comment]
Hi,

yes you are correct,  "from_file" method need to be used instead of open
method on python 2.7.6. but on the other hand "from_file" method is not
available in python 2.7.9 (so from_file method won't work on 2.7.9)...so to
fix that i used the below code which should work irrespective of python
versions...again thanks for letting me know and also i'm glad you figured
it out.

```
def filetype(self):
    if os.path.exists(self.file):
        try:
            m = magic.open(magic.MAGIC_NONE)
            m.load()
            ftype = m.file(self.file)
            return ftype
        except AttributeError:
            ftype = magic.from_file(self.file)
            return ftype
    else:
        print "No such file or directory:", self.file
        sys.exit()
```
